---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: suresh0409/dockerproject:app
   ports:
     - "3306:3306"

 application:
   image: suresh0409/dockerproject:db
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
